import { useMemo } from "react";
import { useAuth } from "../auth/AuthContext";
import { MiniBars } from "../components/charts";
import { Card, DateText, EmptyState, ErrorState, LoadingState, Money, PageHeader, StatusBadge } from "../components/ui";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/api";
import type { CashFlow, DashboardReport, Invoice, Payment, Prediction, Student } from "../types/api";
import { formatDate } from "../utils/date";
import { PIPELINE_LABELS } from "../utils/format";
import { Link } from "../routes/router";

import { useBusiness } from "../business/BusinessContext";

export function DashboardPage() { const { user, can } = useAuth(); const { category, profile } = useBusiness(); const state = useAsync(async () => { const [dashboard, cash, invoices, payments, predictions, students] = await Promise.all([api.get<DashboardReport>("/dashboard"), api.get<CashFlow>("/reports/cash-flow"), can("invoices:read") ? api.get<Invoice[]>("/invoices") : Promise.resolve([]), can("payments:read") ? api.get<Payment[]>("/payments") : Promise.resolve([]), can("ml:read") ? api.get<Prediction[]>("/ml/predictions") : Promise.resolve([]), category === "EDUCATION" && can("school:read") ? api.get<Student[]>("/school/students") : Promise.resolve([])]); return { dashboard, cash, invoices, payments, predictions, students }; }, [can, category]);
  const chart = useMemo(() => state.data?.cash.points.map((p) => ({ label: formatDate(p.date), value: Number(p.inflow), secondary: Number(p.outflow) })) ?? [], [state.data]);
  if (state.loading) return <LoadingState label="در حال آماده‌سازی داشبورد…" />; if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />; const { dashboard: d } = state.data;
  const header = <PageHeader title={`سلام ${user?.first_name ?? ""}، روز خوبی داشته باشید`} description={<>{profile.description} تا تاریخ <DateText value={d.as_of} /></>} action={category === "EDUCATION" && can("school:enroll") ? <Link to="/students" className="button button--primary">ثبت‌نام دانش‌آموز جدید</Link> : can("invoices:write") ? <Link to="/invoices" className="button button--primary">{profile.newInvoice}</Link> : undefined} />;
  if (category === "EDUCATION") return <>{header}<EducationOverview students={state.data.students} canEnroll={can("school:enroll")} canManage={can("school:manage")} /><EducationDashboard students={state.data.students} /></>;
  return <>{header}{category !== "RETAIL" && <section className={`business-overview business-overview--${category.toLowerCase()}`}><div><span className="eyebrow">{profile.name}</span><h2>{profile.title}</h2><p>{profile.workflow}</p></div><div className="business-shortcuts">{can("invoices:read") && <Link to="/invoices">{profile.invoices}</Link>}{can("reports:read") && <Link to="/customers">{profile.customers}</Link>}{can("payments:read") && <Link to="/payments">{profile.receipts}</Link>}{can("products:read") && <Link to="/products">{profile.items}</Link>}</div>{can("invoices:read") && <div className="business-status"><span>پیش‌نویس <b>{state.data.invoices.filter((x) => x.status === "DRAFT").length}</b></span><span>در انتظار تسویه <b>{state.data.invoices.filter((x) => ["ISSUED", "PARTIALLY_PAID"].includes(x.status)).length}</b></span><span>تسویه‌شده <b>{state.data.invoices.filter((x) => x.status === "PAID").length}</b></span></div>}</section>}<section className="kpi-grid"><Kpi title={profile.revenue} value={d.total_revenue} tone="positive"/><Kpi title="هزینه" value={d.total_expenses}/><Kpi title="سود خالص" value={d.net_income} tone={Number(d.net_income) >= 0 ? "positive" : "negative"}/><Kpi title="جریان نقدی خالص" value={d.net_cash_flow}/><Kpi title={profile.outstanding} value={d.outstanding_invoices} note={`${d.outstanding_invoice_count} ${profile.invoice}`}/><Kpi title="مطالبات سررسیدگذشته" value={d.overdue_invoices} note={`${d.overdue_invoice_count} ${profile.invoice}`} tone={Number(d.overdue_invoices) > 0 ? "negative" : "positive"}/></section><section className="dashboard-grid"><Card title="روند دریافت و پرداخت" className="span-2"><div className="chart-legend"><span><i className="legend-inflow"/>دریافت</span><i className="legend-outflow"/><span>پرداخت</span></div><MiniBars data={chart}/></Card><Card title="پیگیری فوری"><div className="attention"><strong>{d.overdue_invoice_count}</strong><span>{profile.invoice} سررسیدگذشته</span><Money value={d.overdue_invoices}/><Link to="/reports/receivables">مشاهده مطالبات ←</Link></div></Card><RecentInvoices items={state.data.invoices.slice(-5).reverse()} /><RecentPayments items={state.data.payments.slice(-5).reverse()} /><AiActivity items={state.data.predictions.slice(0, 5)} /></section></>;
}
function EducationOverview({ students, canEnroll, canManage }: { students: Student[]; canEnroll: boolean; canManage: boolean }) { const enrollments = students.flatMap((student) => student.enrollments); const pending = enrollments.filter((enrollment) => enrollment.status === "PENDING" || enrollment.status === "PARTIALLY_PAID").length; const settled = enrollments.filter((enrollment) => enrollment.status === "PAID").length; return <section className="business-overview business-overview--education"><div><span className="eyebrow">مدیریت آموزشگاه</span><h2>ثبت‌نام و پرونده دانش‌آموزان</h2><p>از این بخش دانش‌آموز ثبت کنید، پرونده‌ها را ببینید و پرداخت‌های شهریه را پیگیری کنید.</p></div><div className="business-shortcuts">{canEnroll && <Link to="/students">ثبت‌نام دانش‌آموز</Link>}<Link to="/student-records">پرونده مشتریان</Link>{canManage && <Link to="/courses">دوره‌ها و شهریه‌ها</Link>}</div><div className="business-status"><span>کل دانش‌آموزان <b>{students.length}</b></span><span>در انتظار تسویه <b>{pending}</b></span><span>تسویه‌شده <b>{settled}</b></span></div></section>; }
function EducationDashboard({ students }: { students: Student[] }) {
  const records = students.flatMap((student) => student.enrollments.map((enrollment) => ({ student, enrollment })));
  const total = records.reduce((sum, item) => sum + Number(item.enrollment.total_amount), 0);
  const collected = records.reduce((sum, item) => sum + Number(item.enrollment.amount_paid), 0);
  const outstanding = records.reduce((sum, item) => sum + Number(item.enrollment.balance_due), 0);
  const today = new Date().toISOString().slice(0, 10);
  const duePayments = records.flatMap(({ student, enrollment }) => enrollment.payments.filter((payment) => payment.status === "PENDING" && payment.due_date && payment.due_date <= today).map((payment) => ({ student, payment }))).sort((a, b) => (a.payment.due_date ?? "").localeCompare(b.payment.due_date ?? ""));
  const openRecords = records.filter(({ enrollment }) => Number(enrollment.balance_due) > 0).sort((a, b) => Number(b.enrollment.balance_due) - Number(a.enrollment.balance_due));
  return <>
    <section className="kpi-grid">
      <Kpi title="مجموع شهریه ثبت‌شده" value={String(total)} tone="positive" note={`${records.length} پرونده ثبت‌نام`} to="/tuition/registered" />
      <Kpi title="شهریه دریافت‌شده" value={String(collected)} tone="positive" note="مبالغ پرداخت‌شده" to="/tuition/received" />
      <Kpi title="مانده شهریه دانش‌آموزان" value={String(outstanding)} tone={outstanding > 0 ? "negative" : "positive"} note={`${openRecords.length} پرونده باز`} to="/tuition/outstanding" />
      <Kpi title="اقساط یا چک‌های سررسیدشده" value={String(duePayments.reduce((sum, item) => sum + Number(item.payment.amount), 0))} tone={duePayments.length ? "negative" : "positive"} note={`${duePayments.length} مورد نیازمند پیگیری`} to="/tuition/due-payments" />
    </section>
    <section className="dashboard-grid">
      <Card title="پرونده‌های دارای مانده شهریه" className="span-2">
        {openRecords.length ? <div className="compact-list">{openRecords.slice(0, 5).map(({ student, enrollment }) => <Link key={enrollment.id} to={`/students/${student.id}`}><span><strong>{student.full_name}</strong><small>{student.grade.replace("GRADE_", "پایه ")}</small></span><span><Money value={enrollment.balance_due} /><small>مانده</small></span></Link>)}</div> : <EmptyState title="همه پرونده‌ها تسویه شده‌اند" detail="دانش‌آموزی با مانده شهریه وجود ندارد." />}
      </Card>
      <Card title="پیگیری سررسیدها">
        {duePayments.length ? <div className="compact-list">{duePayments.slice(0, 5).map(({ student, payment }) => <Link key={payment.id} to={`/students/${student.id}`}><span><strong>{student.full_name}</strong><small>{payment.method === "CHECK" ? "چک" : "قسط"} · <DateText value={payment.due_date ?? ""} /></small></span><Money value={payment.amount} /></Link>)}</div> : <EmptyState title="سررسید معوقی ندارید" detail="چک یا قسط پرداخت‌نشده‌ای تا امروز ثبت نشده است." />}
      </Card>
      <Card title="آخرین ثبت‌نام‌ها">
        {students.length ? <div className="compact-list">{[...students].reverse().slice(0, 5).map((student) => <Link key={student.id} to={`/students/${student.id}`}><span><strong>{student.full_name}</strong><small>{student.grade.replace("GRADE_", "پایه ")} · <DateText value={student.registration_date} /></small></span><span>{student.enrollments.length}<small> پرونده</small></span></Link>)}</div> : <EmptyState title="هنوز دانش‌آموزی ثبت نشده است" detail="از دکمه ثبت‌نام دانش‌آموز جدید شروع کنید." />}
      </Card>
    </section>
  </>;
}
export function Kpi({ title, value, note, tone = "", to }: { title: string; value: string; note?: string; tone?: string; to?: string }) { const content = <><span>{title}</span><Money value={value}/>{note && <small>{note}</small>}</>; return to ? <Link to={to} className={`kpi ${tone} kpi--link`}>{content}</Link> : <article className={`kpi ${tone}`}>{content}</article>; }
function RecentInvoices({ items }: { items: Invoice[] }) { return <Card title="آخرین فاکتورها">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/invoices"><span><strong>{x.invoice_number}</strong><small><DateText value={x.issue_date}/></small></span><span><Money value={x.total}/><StatusBadge value={x.status}/></span></Link>)}</div> : <EmptyState title="فاکتوری ثبت نشده است"/>}</Card>; }
function RecentPayments({ items }: { items: Payment[] }) { return <Card title="آخرین دریافت‌ها">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/payments"><span><strong>{x.reference}</strong><small><DateText value={x.payment_date}/></small></span><span><Money value={x.amount}/><StatusBadge value={x.status}/></span></Link>)}</div> : <EmptyState title="پرداختی ثبت نشده است"/>}</Card>; }
function AiActivity({ items }: { items: Prediction[] }) { return <Card title="فعالیت هوش مصنوعی">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/ai"><span><strong>{PIPELINE_LABELS[x.pipeline]}</strong><small><DateText value={x.predicted_at}/></small></span>{x.review_required && <span className="badge badge--warning">نیازمند بررسی</span>}</Link>)}</div> : <EmptyState title="تحلیلی انجام نشده است" detail="پس از اجرای مدل‌ها، نتایج اینجا دیده می‌شوند."/>}</Card>; }
