import { useState, type FormEvent, type ReactNode } from "react";
import { useAuth } from "../auth/AuthContext";
import { Field } from "../components/ui";
import { Link, useRouter } from "../routes/router";
import { ApiError } from "../services/api";

import { businessProfiles, type BusinessCategory } from "../business/BusinessContext";

function AuthPage({ children }: { children: ReactNode }) {
  return <main className="login-page"><section className="login-intro"><div className="login-mark">آ</div><p className="eyebrow">سامانه مالی یکپارچه</p><h1>حسابداری روشن،<br />تصمیم‌گیری مطمئن.</h1><p>اسناد مالی، گزارش‌های مدیریتی و تحلیل هوشمند کسب‌وکار شما در یک محیط امن و ساده.</p><div className="trust-list"><span>✓ حسابداری دوطرفه</span><span>✓ گزارش‌های واقعی</span><span>✓ تحلیل هوشمند قابل توضیح</span></div></section><section className="login-panel">{children}</section></main>;
}

export function LoginPage() { const { login } = useAuth(); const { navigate } = useRouter(); const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await login(identifier.trim(), password); navigate("/dashboard", true); } catch { setError("ایمیل، شماره تلفن یا رمز عبور صحیح نیست. دوباره تلاش کنید."); } finally { setBusy(false); } };
  return <AuthPage><form onSubmit={submit} className="login-form" autoComplete="off"><header><h2>ورود به حساب کاربری</h2><p>برای ادامه، مشخصات حساب خود را وارد کنید.</p></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<Field label="ایمیل یا شماره تلفن" hint="شماره تلفن را با کد کشور وارد کنید؛ مانند ‎+989121234567"><input type="text" dir="ltr" autoComplete="off" value={identifier} onChange={(e) => setIdentifier(e.target.value)} required autoFocus /></Field><Field label="رمز عبور"><div className="password-input"><input type={showPassword ? "text" : "password"} dir="ltr" autoComplete="off" value={password} onChange={(e) => setPassword(e.target.value)} required /><button type="button" className="password-input__toggle" onClick={() => setShowPassword((current) => !current)} aria-label={showPassword ? "پنهان کردن رمز عبور" : "نمایش رمز عبور"} title={showPassword ? "پنهان کردن رمز عبور" : "نمایش رمز عبور"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" /><circle cx="12" cy="12" r="2.5" />{showPassword && <path d="m4 4 16 16" />}</svg></button></div></Field><button className="button button--primary button--large" disabled={busy}>{busy ? "در حال ورود…" : "ورود به سامانه"}</button><div className="auth-switch"><span>هنوز حساب کاربری ندارید؟</span><Link to="/register" className="button button--secondary">ثبت‌نام</Link></div><small className="secure-note">اطلاعات ورود فقط برای احراز هویت به سرور ارسال می‌شود.</small></form></AuthPage>;
}

export function RegisterPage() { const { register } = useAuth(); const { navigate } = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password")); if (password !== String(form.get("password_confirmation"))) { setError("رمز عبور و تکرار آن یکسان نیستند."); return; } const email = String(form.get("email")).trim(); const phoneNumber = String(form.get("phone_number")).trim(); if (!email && !phoneNumber) { setError("برای ثبت‌نام، ایمیل یا شماره تلفن را وارد کنید."); return; } setBusy(true); setError(""); try { await register({ first_name: String(form.get("first_name")).trim(), last_name: String(form.get("last_name")).trim(), email: email || null, phone_number: phoneNumber || null, password, business_category: String(form.get("business_category")) as BusinessCategory }); navigate("/dashboard", true); } catch (reason) { setError(reason instanceof ApiError && reason.status === 409 ? "حسابی با این نشانی ایمیل یا شماره تلفن قبلاً ثبت شده است." : "ثبت‌نام انجام نشد. لطفاً اطلاعات واردشده را بررسی کنید."); } finally { setBusy(false); } };
  return <AuthPage><form onSubmit={submit} className="login-form"><header><h2>ساخت حساب کاربری</h2><p>برای شروع، حداقل یکی از ایمیل یا شماره تلفن را وارد کنید.</p></header>{error && <div className="alert alert--error" role="alert">{error}</div>}<div className="form-grid form-grid--2"><Field label="نام"><input name="first_name" autoComplete="given-name" maxLength={100} required autoFocus /></Field><Field label="نام خانوادگی"><input name="last_name" autoComplete="family-name" maxLength={100} required /></Field></div><Field label="نوع کسب‌وکار"><select name="business_category" defaultValue="RETAIL" required>{Object.entries(businessProfiles).map(([key, profile]) => <option key={key} value={key}>{profile.name}</option>)}</select></Field><Field label="نشانی ایمیل"><input name="email" type="email" dir="ltr" autoComplete="email" /></Field><Field label="شماره تلفن" hint="با کد کشور، مانند ‎+989121234567"><input name="phone_number" type="tel" dir="ltr" autoComplete="tel" maxLength={16} pattern="\+[1-9][0-9]{7,14}" placeholder="+989121234567" /></Field><Field label="رمز عبور" hint="حداقل ۱۲ نویسه"><input name="password" type="password" dir="ltr" autoComplete="new-password" minLength={12} maxLength={128} required /></Field><Field label="تکرار رمز عبور"><input name="password_confirmation" type="password" dir="ltr" autoComplete="new-password" minLength={12} maxLength={128} required /></Field><button className="button button--primary button--large" disabled={busy}>{busy ? "در حال ساخت حساب…" : "ثبت‌نام و ورود"}</button><div className="auth-switch"><span>قبلاً حساب ساخته‌اید؟</span><Link to="/login" className="text-button">ورود به حساب</Link></div></form></AuthPage>;
}
